services:
  postgres:
    image: postgres:15.17-trixie
    container_name: supporter_unt_db
    environment:
      POSTGRES_DB: supporter_unt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  fastapi:
    build: ./backend-fastapi
    container_name: supporter_unt_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/supporter_unt
      - SECRET_KEY=supersecretkeypleasechangemeinproduction
      - ENCRYPTION_KEY=supersecretencryptionkeymustbe32bytes
    volumes:
      - ./backend-fastapi:/app
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
