version: '3.8'

services:
  postgres:
    image: postgres:15.17-trixie
    container_name: supporter_unt_db
    environment:
      POSTGRES_DB: supporter_unt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
